# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itkUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1100, 649)
        self.centralwidget = QtGui.QWidget(Form)
        self.centralwidget.setGeometry(QtCore.QRect(10, 30, 1081, 601))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 19, 91, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.bp_newItk = QtGui.QPushButton(self.centralwidget)
        self.bp_newItk.setGeometry(QtCore.QRect(30, 560, 191, 27))
        self.bp_newItk.setObjectName(_fromUtf8("bp_newItk"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 50, 1031, 241))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1014, 239))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bp_saveItk = QtGui.QPushButton(self.centralwidget)
        self.bp_saveItk.setGeometry(QtCore.QRect(430, 560, 161, 27))
        self.bp_saveItk.setObjectName(_fromUtf8("bp_saveItk"))
        self.bp_supItk = QtGui.QPushButton(self.centralwidget)
        self.bp_supItk.setGeometry(QtCore.QRect(230, 560, 191, 27))
        self.bp_supItk.setObjectName(_fromUtf8("bp_supItk"))
        self.line_nomIti = QtGui.QLineEdit(self.centralwidget)
        self.line_nomIti.setGeometry(QtCore.QRect(320, 10, 311, 27))
        self.line_nomIti.setObjectName(_fromUtf8("line_nomIti"))
        self.bp_prevItk = QtGui.QPushButton(self.centralwidget)
        self.bp_prevItk.setGeometry(QtCore.QRect(670, 560, 41, 27))
        self.bp_prevItk.setObjectName(_fromUtf8("bp_prevItk"))
        self.bp_plante = QtGui.QPushButton(self.centralwidget)
        self.bp_plante.setEnabled(True)
        self.bp_plante.setGeometry(QtCore.QRect(970, 320, 91, 31))
        self.bp_plante.setObjectName(_fromUtf8("bp_plante"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(30, 310, 341, 221))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.bp_supPlante = QtGui.QPushButton(self.frame_3)
        self.bp_supPlante.setGeometry(QtCore.QRect(180, 170, 85, 27))
        self.bp_supPlante.setObjectName(_fromUtf8("bp_supPlante"))
        self.combo_nomPlante = QtGui.QComboBox(self.frame_3)
        self.combo_nomPlante.setGeometry(QtCore.QRect(70, 70, 241, 27))
        self.combo_nomPlante.setObjectName(_fromUtf8("combo_nomPlante"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 56, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.bp_addPlante = QtGui.QPushButton(self.frame_3)
        self.bp_addPlante.setGeometry(QtCore.QRect(110, 170, 61, 27))
        self.bp_addPlante.setObjectName(_fromUtf8("bp_addPlante"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 50, 56, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 121, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.bp_savePlante = QtGui.QPushButton(self.frame_3)
        self.bp_savePlante.setGeometry(QtCore.QRect(20, 170, 85, 27))
        self.bp_savePlante.setObjectName(_fromUtf8("bp_savePlante"))
        self.line_semPlant = QtGui.QLineEdit(self.frame_3)
        self.line_semPlant.setGeometry(QtCore.QRect(140, 100, 51, 27))
        self.line_semPlant.setObjectName(_fromUtf8("line_semPlant"))
        self.combo_idPlante = QtGui.QComboBox(self.frame_3)
        self.combo_idPlante.setGeometry(QtCore.QRect(70, 40, 71, 27))
        self.combo_idPlante.setObjectName(_fromUtf8("combo_idPlante"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(130, 10, 56, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bp_action = QtGui.QPushButton(self.centralwidget)
        self.bp_action.setEnabled(True)
        self.bp_action.setGeometry(QtCore.QRect(970, 360, 91, 31))
        self.bp_action.setObjectName(_fromUtf8("bp_action"))
        self.bp_nextItk = QtGui.QPushButton(self.centralwidget)
        self.bp_nextItk.setGeometry(QtCore.QRect(720, 560, 41, 27))
        self.bp_nextItk.setObjectName(_fromUtf8("bp_nextItk"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(380, 310, 331, 221))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.bp_supAction = QtGui.QPushButton(self.frame_4)
        self.bp_supAction.setGeometry(QtCore.QRect(180, 170, 85, 27))
        self.bp_supAction.setObjectName(_fromUtf8("bp_supAction"))
        self.combo_nomAction = QtGui.QComboBox(self.frame_4)
        self.combo_nomAction.setGeometry(QtCore.QRect(70, 70, 241, 27))
        self.combo_nomAction.setObjectName(_fromUtf8("combo_nomAction"))
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.bp_addAction = QtGui.QPushButton(self.frame_4)
        self.bp_addAction.setGeometry(QtCore.QRect(110, 170, 61, 27))
        self.bp_addAction.setObjectName(_fromUtf8("bp_addAction"))
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 56, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(20, 110, 141, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.bp_saveAction = QtGui.QPushButton(self.frame_4)
        self.bp_saveAction.setGeometry(QtCore.QRect(20, 170, 85, 27))
        self.bp_saveAction.setObjectName(_fromUtf8("bp_saveAction"))
        self.line_semAction = QtGui.QLineEdit(self.frame_4)
        self.line_semAction.setGeometry(QtCore.QRect(160, 100, 51, 27))
        self.line_semAction.setObjectName(_fromUtf8("line_semAction"))
        self.combo_idAction = QtGui.QComboBox(self.frame_4)
        self.combo_idAction.setGeometry(QtCore.QRect(70, 40, 71, 27))
        self.combo_idAction.setObjectName(_fromUtf8("combo_idAction"))
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(130, 10, 56, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.line_dureeAction = QtGui.QLineEdit(self.frame_4)
        self.line_dureeAction.setGeometry(QtCore.QRect(160, 130, 51, 27))
        self.line_dureeAction.setObjectName(_fromUtf8("line_dureeAction"))
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(110, 140, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.menubar = QtGui.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.statusbar = QtGui.QStatusBar(Form)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 22))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Itineraire technique", None))
        self.label_8.setText(_translate("Form", "Nom itineraire", None))
        self.bp_newItk.setText(_translate("Form", "Nouvel itineraire technique", None))
        self.bp_saveItk.setText(_translate("Form", "Enregistrer l\'itinéraire", None))
        self.bp_supItk.setText(_translate("Form", "Supprimer itineraire en cours", None))
        self.bp_prevItk.setText(_translate("Form", "<<", None))
        self.bp_plante.setText(_translate("Form", "Gerer plantes", None))
        self.bp_supPlante.setText(_translate("Form", "Supprimer", None))
        self.label_9.setText(_translate("Form", "Plante:", None))
        self.bp_addPlante.setText(_translate("Form", "Ajouter", None))
        self.label_11.setText(_translate("Form", "Ligne N°", None))
        self.label_10.setText(_translate("Form", "Semaine plantation:", None))
        self.bp_savePlante.setText(_translate("Form", "Enregistrer", None))
        self.label_12.setText(_translate("Form", "PLANTE", None))
        self.bp_action.setText(_translate("Form", "Gerer actions", None))
        self.bp_nextItk.setText(_translate("Form", ">>", None))
        self.bp_supAction.setText(_translate("Form", "Supprimer", None))
        self.label_13.setText(_translate("Form", "Action:", None))
        self.bp_addAction.setText(_translate("Form", "Ajouter", None))
        self.label_14.setText(_translate("Form", "Ligne N°", None))
        self.label_15.setText(_translate("Form", "Semaine mise en place:", None))
        self.bp_saveAction.setText(_translate("Form", "Enregistrer", None))
        self.label_16.setText(_translate("Form", "Action", None))
        self.label_17.setText(_translate("Form", "Durée:", None))

