# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maraichageUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1101, 721)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 10))
        MainWindow.setBaseSize(QtCore.QSize(0, 1000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 40, 1025, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 400))
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 10))
        self.scrollArea.setBaseSize(QtCore.QSize(500, 1000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1008, 4000))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 4000))
        self.scrollAreaWidgetContents.setBaseSize(QtCore.QSize(400, 4000))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BP_listSemis = QtGui.QPushButton(self.centralwidget)
        self.BP_listSemis.setGeometry(QtCore.QRect(730, 600, 151, 27))
        self.BP_listSemis.setObjectName(_fromUtf8("BP_listSemis"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(500, 0, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setGeometry(QtCore.QRect(450, 0, 41, 21))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(560, 0, 41, 21))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.BP_listAction = QtGui.QPushButton(self.centralwidget)
        self.BP_listAction.setGeometry(QtCore.QRect(890, 600, 151, 27))
        self.BP_listAction.setObjectName(_fromUtf8("BP_listAction"))
        self.BP_itk = QtGui.QPushButton(self.centralwidget)
        self.BP_itk.setGeometry(QtCore.QRect(590, 560, 131, 27))
        self.BP_itk.setObjectName(_fromUtf8("BP_itk"))
        self.frame_7 = QtGui.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(40, 550, 501, 91))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.comboItk = QtGui.QComboBox(self.frame_7)
        self.comboItk.setGeometry(QtCore.QRect(320, 10, 161, 27))
        self.comboItk.setObjectName(_fromUtf8("comboItk"))
        self.label_19 = QtGui.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(290, 20, 31, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.BP_supPlanche = QtGui.QPushButton(self.frame_7)
        self.BP_supPlanche.setGeometry(QtCore.QRect(330, 50, 151, 27))
        self.BP_supPlanche.setObjectName(_fromUtf8("BP_supPlanche"))
        self.comboPlanche = QtGui.QComboBox(self.frame_7)
        self.comboPlanche.setGeometry(QtCore.QRect(120, 10, 161, 27))
        self.comboPlanche.setObjectName(_fromUtf8("comboPlanche"))
        self.label_18 = QtGui.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.BP_savePlanche = QtGui.QPushButton(self.frame_7)
        self.BP_savePlanche.setGeometry(QtCore.QRect(150, 50, 161, 27))
        self.BP_savePlanche.setObjectName(_fromUtf8("BP_savePlanche"))
        self.BP_newPlanche = QtGui.QPushButton(self.frame_7)
        self.BP_newPlanche.setGeometry(QtCore.QRect(10, 50, 121, 27))
        self.BP_newPlanche.setObjectName(_fromUtf8("BP_newPlanche"))
        self.BP_planche = QtGui.QPushButton(self.centralwidget)
        self.BP_planche.setGeometry(QtCore.QRect(590, 600, 131, 27))
        self.BP_planche.setObjectName(_fromUtf8("BP_planche"))
        self.BP_listRecolte = QtGui.QPushButton(self.centralwidget)
        self.BP_listRecolte.setGeometry(QtCore.QRect(890, 640, 151, 27))
        self.BP_listRecolte.setObjectName(_fromUtf8("BP_listRecolte"))
        self.BP_recharge = QtGui.QPushButton(self.centralwidget)
        self.BP_recharge.setGeometry(QtCore.QRect(590, 640, 131, 27))
        self.BP_recharge.setObjectName(_fromUtf8("BP_recharge"))
        self.BP_plante = QtGui.QPushButton(self.centralwidget)
        self.BP_plante.setGeometry(QtCore.QRect(730, 560, 151, 27))
        self.BP_plante.setObjectName(_fromUtf8("BP_plante"))
        self.BP_action = QtGui.QPushButton(self.centralwidget)
        self.BP_action.setGeometry(QtCore.QRect(890, 560, 151, 27))
        self.BP_action.setObjectName(_fromUtf8("BP_action"))
        self.BP_listPlantation = QtGui.QPushButton(self.centralwidget)
        self.BP_listPlantation.setGeometry(QtCore.QRect(730, 640, 151, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BP_listPlantation.sizePolicy().hasHeightForWidth())
        self.BP_listPlantation.setSizePolicy(sizePolicy)
        self.BP_listPlantation.setObjectName(_fromUtf8("BP_listPlantation"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestion assolement", None))
        self.BP_listSemis.setText(_translate("MainWindow", "Voir le listing des semis", None))
        self.label_17.setText(_translate("MainWindow", "2017", None))
        self.pushButton_8.setText(_translate("MainWindow", "<<", None))
        self.pushButton_9.setText(_translate("MainWindow", ">>", None))
        self.BP_listAction.setText(_translate("MainWindow", "Voir le listing des actions", None))
        self.BP_itk.setText(_translate("MainWindow", "Gerer les itineraires", None))
        self.label_19.setText(_translate("MainWindow", "ITK", None))
        self.BP_supPlanche.setText(_translate("MainWindow", "Supprimer planche", None))
        self.label_18.setText(_translate("MainWindow", "Planche active", None))
        self.BP_savePlanche.setText(_translate("MainWindow", "Enregistrer les planches", None))
        self.BP_newPlanche.setText(_translate("MainWindow", "Nouvelle planche", None))
        self.BP_planche.setText(_translate("MainWindow", "Gerer les planches", None))
        self.BP_listRecolte.setText(_translate("MainWindow", "Voir le listing des recoltes", None))
        self.BP_recharge.setText(_translate("MainWindow", "Recharger", None))
        self.BP_plante.setText(_translate("MainWindow", "Gerer les plantes", None))
        self.BP_action.setText(_translate("MainWindow", "Gerer les actions", None))
        self.BP_listPlantation.setText(_translate("MainWindow", "Listing des plantations", None))

