# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'planteUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(606, 474)
        self.centralwidget = QtGui.QWidget(Form)
        self.centralwidget.setGeometry(QtCore.QRect(0, 40, 601, 417))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.bp_lastPlante = QtGui.QPushButton(self.centralwidget)
        self.bp_lastPlante.setGeometry(QtCore.QRect(30, 380, 41, 27))
        self.bp_lastPlante.setObjectName(_fromUtf8("bp_lastPlante"))
        self.bp_nextPlante = QtGui.QPushButton(self.centralwidget)
        self.bp_nextPlante.setGeometry(QtCore.QRect(80, 380, 41, 27))
        self.bp_nextPlante.setObjectName(_fromUtf8("bp_nextPlante"))
        self.bp_newPlante = QtGui.QPushButton(self.centralwidget)
        self.bp_newPlante.setGeometry(QtCore.QRect(130, 380, 111, 27))
        self.bp_newPlante.setObjectName(_fromUtf8("bp_newPlante"))
        self.bp_supPlante = QtGui.QPushButton(self.centralwidget)
        self.bp_supPlante.setGeometry(QtCore.QRect(250, 380, 161, 27))
        self.bp_supPlante.setObjectName(_fromUtf8("bp_supPlante"))
        self.bp_SavePlante = QtGui.QPushButton(self.centralwidget)
        self.bp_SavePlante.setGeometry(QtCore.QRect(420, 380, 151, 27))
        self.bp_SavePlante.setObjectName(_fromUtf8("bp_SavePlante"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 50, 541, 311))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.line_ageFleur = QtGui.QLineEdit(self.tab)
        self.line_ageFleur.setEnabled(True)
        self.line_ageFleur.setGeometry(QtCore.QRect(130, 130, 41, 27))
        self.line_ageFleur.setObjectName(_fromUtf8("line_ageFleur"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 81, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 81, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line_nom2 = QtGui.QLineEdit(self.tab)
        self.line_nom2.setGeometry(QtCore.QRect(130, 20, 351, 27))
        self.line_nom2.setObjectName(_fromUtf8("line_nom2"))
        self.line_ageRecolte = QtGui.QLineEdit(self.tab)
        self.line_ageRecolte.setGeometry(QtCore.QRect(130, 70, 41, 27))
        self.line_ageRecolte.setObjectName(_fromUtf8("line_ageRecolte"))
        self.check_tallage = QtGui.QCheckBox(self.tab)
        self.check_tallage.setEnabled(True)
        self.check_tallage.setGeometry(QtCore.QRect(200, 170, 87, 22))
        self.check_tallage.setObjectName(_fromUtf8("check_tallage"))
        self.check_annuelle = QtGui.QCheckBox(self.tab)
        self.check_annuelle.setGeometry(QtCore.QRect(30, 170, 87, 22))
        self.check_annuelle.setObjectName(_fromUtf8("check_annuelle"))
        self.check_vernalisation = QtGui.QCheckBox(self.tab)
        self.check_vernalisation.setEnabled(True)
        self.check_vernalisation.setGeometry(QtCore.QRect(30, 200, 171, 22))
        self.check_vernalisation.setObjectName(_fromUtf8("check_vernalisation"))
        self.check_gelive = QtGui.QCheckBox(self.tab)
        self.check_gelive.setEnabled(True)
        self.check_gelive.setGeometry(QtCore.QRect(120, 170, 87, 22))
        self.check_gelive.setObjectName(_fromUtf8("check_gelive"))
        self.textInfo = QtGui.QTextEdit(self.tab)
        self.textInfo.setEnabled(True)
        self.textInfo.setGeometry(QtCore.QRect(320, 90, 181, 171))
        self.textInfo.setObjectName(_fromUtf8("textInfo"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(320, 70, 131, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(40, 100, 81, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.line_duree_recolte = QtGui.QLineEdit(self.tab)
        self.line_duree_recolte.setGeometry(QtCore.QRect(130, 100, 41, 27))
        self.line_duree_recolte.setObjectName(_fromUtf8("line_duree_recolte"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(200, 190, 131, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.line_dist_x = QtGui.QLineEdit(self.tab_3)
        self.line_dist_x.setGeometry(QtCore.QRect(150, 110, 41, 27))
        self.line_dist_x.setObjectName(_fromUtf8("line_dist_x"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(210, 130, 131, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 131, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_rendement = QtGui.QLineEdit(self.tab_3)
        self.line_rendement.setGeometry(QtCore.QRect(150, 190, 41, 27))
        self.line_rendement.setObjectName(_fromUtf8("line_rendement"))
        self.line_dist_y = QtGui.QLineEdit(self.tab_3)
        self.line_dist_y.setGeometry(QtCore.QRect(150, 150, 41, 27))
        self.line_dist_y.setObjectName(_fromUtf8("line_dist_y"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 131, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 131, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineSemis = QtGui.QLineEdit(self.tab_3)
        self.lineSemis.setEnabled(True)
        self.lineSemis.setGeometry(QtCore.QRect(150, 30, 81, 27))
        self.lineSemis.setObjectName(_fromUtf8("lineSemis"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 121, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 171, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.line_duree_pepiniere = QtGui.QLineEdit(self.tab_3)
        self.line_duree_pepiniere.setGeometry(QtCore.QRect(190, 70, 31, 27))
        self.line_duree_pepiniere.setObjectName(_fromUtf8("line_duree_pepiniere"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 230, 131, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.line_graineparg = QtGui.QLineEdit(self.tab_3)
        self.line_graineparg.setGeometry(QtCore.QRect(150, 230, 41, 27))
        self.line_graineparg.setObjectName(_fromUtf8("line_graineparg"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineRetour = QtGui.QLineEdit(self.tab_2)
        self.lineRetour.setEnabled(True)
        self.lineRetour.setGeometry(QtCore.QRect(170, 20, 41, 27))
        self.lineRetour.setObjectName(_fromUtf8("lineRetour"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineNoC = QtGui.QLineEdit(self.tab_2)
        self.lineNoC.setEnabled(True)
        self.lineNoC.setGeometry(QtCore.QRect(170, 60, 41, 27))
        self.lineNoC.setObjectName(_fromUtf8("lineNoC"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(80, 60, 81, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.line_nomPlante = QtGui.QLineEdit(self.centralwidget)
        self.line_nomPlante.setGeometry(QtCore.QRect(120, 10, 291, 27))
        self.line_nomPlante.setObjectName(_fromUtf8("line_nomPlante"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 71, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.menubar = QtGui.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.statusbar = QtGui.QStatusBar(Form)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 22))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        self.NewPlante = QtGui.QAction(Form)
        self.NewPlante.setObjectName(_fromUtf8("NewPlante"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.bp_newPlante, QtCore.SIGNAL(_fromUtf8("clicked()")), self.NewPlante.trigger)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Fiche plante", None))
        self.bp_lastPlante.setText(_translate("Form", "<<", None))
        self.bp_nextPlante.setText(_translate("Form", ">>", None))
        self.bp_newPlante.setText(_translate("Form", "Nouvelle plante", None))
        self.bp_supPlante.setText(_translate("Form", "Supprimer plante en cours", None))
        self.bp_SavePlante.setText(_translate("Form", "Enregistre la plante", None))
        self.label_4.setText(_translate("Form", "Age floraison", None))
        self.label_3.setText(_translate("Form", "Age récolte", None))
        self.label_2.setText(_translate("Form", "Nom commercial", None))
        self.check_tallage.setText(_translate("Form", "Tallage", None))
        self.check_annuelle.setText(_translate("Form", "Annuelle", None))
        self.check_vernalisation.setText(_translate("Form", "Vernalisation necessaire", None))
        self.check_gelive.setText(_translate("Form", "Gelive", None))
        self.label_14.setText(_translate("Form", "info complémentaire:", None))
        self.label_16.setText(_translate("Form", "Durée récolte", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Généralité", None))
        self.label_9.setText(_translate("Form", "Rendement au m2 :", None))
        self.label_7.setText(_translate("Form", "Plant au m2 :", None))
        self.label_5.setText(_translate("Form", "Distance plantation x", None))
        self.label_6.setText(_translate("Form", "Distance plantation y", None))
        self.label_8.setText(_translate("Form", "Rendement par pied", None))
        self.lineSemis.setText(_translate("Form", "0,1,2", None))
        self.label_12.setText(_translate("Form", "Semis optimal (sem)", None))
        self.label_13.setText(_translate("Form", "Age plantation optimal (sem)", None))
        self.line_duree_pepiniere.setText(_translate("Form", "3", None))
        self.label_15.setText(_translate("Form", "nb graine au grame", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Plantation", None))
        self.label_11.setText(_translate("Form", "Retour au sol (kg C / m2)", None))
        self.label_10.setText(_translate("Form", "Indice N/C %", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Non travail du sol", None))
        self.label.setText(_translate("Form", "Nom plante", None))
        self.NewPlante.setText(_translate("Form", "test", None))

